### ISSUE TITLE
runing some errors happens!

### ISSUE THREAD

**Issue by tomjeans** [1079863482/yolo-fatest-deepsort#1]
when running the code,error happens!
Traceback (most recent call last):
  File "demo.py", line 46, in <module>
    main()
  File "demo.py", line 15, in main
    det = Detector()
  File "/home/nvidia/yolo-fatest-deepsort-main/Detector_pytorch.py", line 10, in __init__
    self.init_model()
  File "/home/nvidia/yolo-fatest-deepsort-main/Detector_pytorch.py", line 24, in init_model
    load_darknet_weights(self.model, coco_weights)
  File "/home/nvidia/yolo-fatest-deepsort-main/utils/models.py", line 394, in load_darknet_weights
    conv.weight.data.copy_(torch.from_numpy(weights[ptr:ptr + nw]).view_as(conv.weight))
RuntimeError: shape '[96, 448, 1, 1]' is invalid for input of size 26694
Could you help me? Thanks.

**Comment by cylel** [comment]
Have you solved this problem? I've encountered the same question

**Comment by tomjeans** [comment]
It works after setting the correct cfg files !
